export default {
  SET_VIEW_ID: 'SET_VIEW_ID',
  FETCH_DATA: 'FETCH_DATA',
  FETCH_LOADING: 'FETCH_LOADING',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_ERROR: 'FETCH_ERROR',
  SET_DATA: 'SET_DATA',
};
