const {
  NODE_ENV,
  BABEL_ENV,
  API_URI,
  API_VERSION,
  MIXPANEL_TOKEN,
  MIXPANEL_TOKEN_SECRET,
  SENTRY_APP_ID,
  SENTRY_APP_KEY,
} = process.env;

module.exports = {
  NODE_ENV: NODE_ENV || 'development',
  BABEL_ENV: BABEL_ENV || 'development',
  API_URI: API_URI || '/api',
  API_VERSION: API_VERSION || 1,
  MIXPANEL_TOKEN,
  MIXPANEL_TOKEN_SECRET,
  SENTRY_APP_ID,
  SENTRY_APP_KEY,
};
